#############################################################################
# Makefile for building: piResiduos
# Generated by qmake (2.01a) (Qt 4.8.7) on: mié mar 3 15:41:17 2021
# Project:  piResiduos.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile piResiduos.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=gnu++11 -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/opt/pvb/pvserver -I/opt/pvb/rllib/lib -I/usr/include/libusb-1.0 -IWacomGSS/include -Ilib -Ilib/SmtpClient-for-Qt/src -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu ./WacomGSS/build/Linux/x86_64/WacomGSS.a /usr/lib/libpvsmt.so /usr/lib/librllib.so -lboost_system -lboost_thread -lusb-1.0 -lcrypto -lssl -lrt -lhpdf -lcups ./lib/SmtpClient-for-Qt/libSMTPEmail.so -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mask10.cpp \
		mask9.cpp \
		mask8.cpp \
		mask7.cpp \
		mask6.cpp \
		mask5.cpp \
		mask4.cpp \
		mask3.cpp \
		camera.cpp \
		mask2.cpp \
		mask1.cpp \
		qtdatabase.cpp \
		database.cpp \
		bascula.cpp \
		outputForm.cpp \
		inputForm.cpp \
		formulario.cpp \
		tableta.cpp \
		station.cpp \
		costumer.cpp \
		ini.cpp \
		mail.cpp \
		generic_tools.cpp \
		staff.cpp \
		driver.cpp 
OBJECTS       = main.o \
		mask10.o \
		mask9.o \
		mask8.o \
		mask7.o \
		mask6.o \
		mask5.o \
		mask4.o \
		mask3.o \
		camera.o \
		mask2.o \
		mask1.o \
		qtdatabase.o \
		database.o \
		bascula.o \
		outputForm.o \
		inputForm.o \
		formulario.o \
		tableta.o \
		station.o \
		costumer.o \
		ini.o \
		mail.o \
		generic_tools.o \
		staff.o \
		driver.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		piResiduos.pro
QMAKE_TARGET  = piResiduos
DESTDIR       = 
TARGET        = piResiduos

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: piResiduos.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile piResiduos.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile piResiduos.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/piResiduos1.0.0 || $(MKDIR) .tmp/piResiduos1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/piResiduos1.0.0/ && $(COPY_FILE) --parents pvapp.h mask10_tools.h mask10_data.h mask10_slots.h mask9_tools.h mask9_data.h mask9_slots.h mask8_tools.h mask8_data.h mask8_slots.h mask7_tools.h mask7_data.h mask7_slots.h mask6_tools.h mask6_data.h mask6_slots.h mask_tools.h mask5_actualiza.h mask5_tools.h mask5_data.h mask5_slots.h mask4_actualiza.h mask4_tools.h mask4_data.h mask4_slots.h mask3_slots.h camera.h mask2_actualiza.h mask2_tools.h mask2_data.h mask2_slots.h mask1_slots.h qtdatabase.h database.h bascula.h outputForm.h inputForm.h formulario.h tableta.h costumer.h station.h ini.h mail.h generic_tools.h staff.h driver.h .tmp/piResiduos1.0.0/ && $(COPY_FILE) --parents main.cpp mask10.cpp mask9.cpp mask8.cpp mask7.cpp mask6.cpp mask5.cpp mask4.cpp mask3.cpp camera.cpp mask2.cpp mask1.cpp qtdatabase.cpp database.cpp bascula.cpp outputForm.cpp inputForm.cpp formulario.cpp tableta.cpp station.cpp costumer.cpp ini.cpp mail.cpp generic_tools.cpp staff.cpp driver.cpp .tmp/piResiduos1.0.0/ && (cd `dirname .tmp/piResiduos1.0.0` && $(TAR) piResiduos1.0.0.tar piResiduos1.0.0 && $(COMPRESS) piResiduos1.0.0.tar) && $(MOVE) `dirname .tmp/piResiduos1.0.0`/piResiduos1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/piResiduos1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mask10.o: mask10.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask10_slots.h \
		mask10_data.h \
		mask10_tools.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask10.o mask10.cpp

mask9.o: mask9.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask9_slots.h \
		mask9_data.h \
		mask9_tools.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask9.o mask9.cpp

mask8.o: mask8.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask8_slots.h \
		mask8_data.h \
		mask8_tools.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask8.o mask8.cpp

mask7.o: mask7.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask7_slots.h \
		mask7_data.h \
		mask7_tools.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask7.o mask7.cpp

mask6.o: mask6.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask6_slots.h \
		mask6_data.h \
		mask6_tools.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask6.o mask6.cpp

mask5.o: mask5.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask5_slots.h \
		tableta.h \
		WacomGSS/include/WacomGSS/STU/getUsbDevices.hpp \
		WacomGSS/include/WacomGSS/STU/UsbInterface.hpp \
		WacomGSS/include/WacomGSS/STU/ReportHandler.hpp \
		WacomGSS/include/WacomGSS/STU/ProtocolHelper.hpp \
		WacomGSS/include/WacomGSS/STU/InterfaceQueue.hpp \
		WacomGSS/include/WacomGSS/STU/Tablet_OpenSSL.hpp \
		mask5_data.h \
		mask_tools.h \
		mask5_tools.h \
		mask5_actualiza.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask5.o mask5.cpp

mask4.o: mask4.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask4_slots.h \
		tableta.h \
		WacomGSS/include/WacomGSS/STU/getUsbDevices.hpp \
		WacomGSS/include/WacomGSS/STU/UsbInterface.hpp \
		WacomGSS/include/WacomGSS/STU/ReportHandler.hpp \
		WacomGSS/include/WacomGSS/STU/ProtocolHelper.hpp \
		WacomGSS/include/WacomGSS/STU/InterfaceQueue.hpp \
		WacomGSS/include/WacomGSS/STU/Tablet_OpenSSL.hpp \
		mask4_data.h \
		mask_tools.h \
		mask4_tools.h \
		mask4_actualiza.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask4.o mask4.cpp

mask3.o: mask3.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask3_slots.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask3.o mask3.cpp

camera.o: camera.cpp camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

mask2.o: mask2.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask2_slots.h \
		mask2_data.h \
		mask_tools.h \
		mask2_tools.h \
		mask2_actualiza.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask2.o mask2.cpp

mask1.o: mask1.cpp pvapp.h \
		camera.h \
		ini.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		bascula.h \
		formulario.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h \
		inputForm.h \
		outputForm.h \
		mail.h \
		mask1_slots.h \
		mask_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask1.o mask1.cpp

qtdatabase.o: qtdatabase.cpp qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtdatabase.o qtdatabase.cpp

database.o: database.cpp database.h \
		generic_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

bascula.o: bascula.cpp bascula.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bascula.o bascula.cpp

outputForm.o: outputForm.cpp outputForm.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		station.h \
		formulario.h \
		costumer.h \
		staff.h \
		driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputForm.o outputForm.cpp

inputForm.o: inputForm.cpp inputForm.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		station.h \
		formulario.h \
		costumer.h \
		staff.h \
		driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputForm.o inputForm.cpp

formulario.o: formulario.cpp formulario.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formulario.o formulario.cpp

tableta.o: tableta.cpp tableta.h \
		WacomGSS/include/WacomGSS/STU/getUsbDevices.hpp \
		WacomGSS/include/WacomGSS/STU/UsbInterface.hpp \
		WacomGSS/include/WacomGSS/STU/ReportHandler.hpp \
		WacomGSS/include/WacomGSS/STU/ProtocolHelper.hpp \
		WacomGSS/include/WacomGSS/STU/InterfaceQueue.hpp \
		WacomGSS/include/WacomGSS/STU/Tablet_OpenSSL.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableta.o tableta.cpp

station.o: station.cpp station.h \
		database.h \
		generic_tools.h \
		qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o station.o station.cpp

costumer.o: costumer.cpp costumer.h \
		database.h \
		generic_tools.h \
		qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o costumer.o costumer.cpp

ini.o: ini.cpp ini.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ini.o ini.cpp

mail.o: mail.cpp mail.h \
		formulario.h \
		generic_tools.h \
		qtdatabase.h \
		database.h \
		station.h \
		costumer.h \
		staff.h \
		driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mail.o mail.cpp

generic_tools.o: generic_tools.cpp generic_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generic_tools.o generic_tools.cpp

staff.o: staff.cpp staff.h \
		database.h \
		generic_tools.h \
		qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staff.o staff.cpp

driver.o: driver.cpp driver.h \
		database.h \
		generic_tools.h \
		qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driver.o driver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

